# linex Project
name: linex Project Compiler v3.0
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        default: 'Tes kernel_kernel'
        required: true
        type: string
      compiler:
        description: 'Compiler | gcc|clang|llvm|other|gcc2|clang2|llvm2'
        default: 'clang'
        required: true
        type: string
      aosp-clang:
        description: 'Clang | false for prebuilt ubuntu'
        default: 'https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz'
        required: true
        type: string
      package:
        description: 'Package for other|gcc2|clang2|llvm2'
        default: 'sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd cpio lld llvm g++-aarch64-linux-gnu libelf-dev neofetch'
        required: true
        type: string
      command:
        description: 'Command+ for other|gcc2|clang2|llvm2'
        default: 'LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld'
        required: true
        type: string
      kernel-url:
        description: 'Kernel-url'
        default: 'https://github.com/KAGA-KOKO/kernel-oppo6765.git'
        required: true
        type: string
      kernel-branch:
        description: 'Kernel-branch'
        default: 'base-oss'
        required: true
        type: string
      kernel-config:
        description: 'Kernel-config'
        default: 'oppo6765_19451_defconfig'
        required: true
        type: string
      disable-lto:
        description: 'Disable LTO'
        default: 'true'
        required: true
        type: string
jobs:
  linex-compiler-v3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkin
      run: |
         echo "name: ${{ inputs.name }}"
         echo "compiler: ${{ inputs.compiler }}"
         echo "aosp-clang: ${{ inputs.aosp-clang }}"
         if [ ${{ inputs.compiler }} == other ]; then
            echo "package: ${{ inputs.package }}"
            echo "command: ${{ inputs.command }}"
         fi
         if [ ${{ inputs.kernel-url }} != false ]; then
            echo "kernel-url: ${{ inputs.kernel-url }}"
            echo "kernel-branch: ${{ inputs.kernel-branch }}"
         fi
         if [ ${{ inputs.kernel-url }} == false ]; then
            echo "kernel-url: use current repo"
            if [ ${{ inputs.kernel-branch }} != main ]; then
               echo "custom-sc: ${{ inputs.kernel-branch }}"
            fi
            if [ ${{ inputs.kernel-branch }} == main ]; then
               echo "custom-sc: disable"
            fi
         fi
         echo "kernel-config: ${{ inputs.kernel-config }}"
         echo "disable-lto: ${{ inputs.disable-lto }}"
         echo "linex Project"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Packages
      run: |
         sudo apt-get update
         sudo apt-get install --no-install-recommends -y binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 aria2
         if [ ${{ inputs.compiler }} == gcc ]; then
             sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd
         fi
         if [ ${{ inputs.compiler }} == llvm ]; then
             sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd
             sudo apt-get install --no-install-recommends -y cpio lld llvm g++-aarch64-linux-gnu libelf-dev neofetch
         fi
         if [ ${{ inputs.compiler }} == other ]; then
             ${{ inputs.package }}
         fi
         if [ ${{ inputs.compiler }} == clang2 ]; then
             ${{ inputs.package }}
         fi
         if [ ${{ inputs.compiler }} == gcc2 ]; then
             sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd
             ${{ inputs.package }}
         fi
         if [ ${{ inputs.compiler }} == llvm2 ]; then
             sudo apt-get install --no-install-recommends -y clang gcc gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu libffi-dev libncurses5-dev libreadline-dev libsqlite3-dev pigz libarchive-tools software-properties-common openssl ssh wget nano ca-certificates zstd
             sudo apt-get install --no-install-recommends -y cpio lld llvm g++-aarch64-linux-gnu libelf-dev neofetch
             ${{ inputs.package }}
         fi
         aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q
         if [ -f /bin/swapon ]; then
             export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
             sudo swapoff $SWAP_FILE
             sudo rm $SWAP_FILE
             sudo fallocate -l 16G $SWAP_FILE
             sudo chmod 600 $SWAP_FILE
             sudo mkswap $SWAP_FILE
             sudo swapon $SWAP_FILE
             unset SWAP_FILE
         fi
    - name: Setup GCC
      run: |
         if [ ${{ inputs.aosp-clang }} == false ]; then
            echo "Using prebuilt gcc"
         else
            mkdir -p -v $HOME/gcc-64
            aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/0a0604336d4d1067aa1aaef8d3779b31fcee841d.tar.gz
            tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
            mkdir -p -v $HOME/gcc-32
            aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/4d16d93f49c2b5ecdd0f12c38d194835dd595603.tar.gz
            tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
         fi
    - name: Setup Clang
      run: |
         if [ ${{ inputs.aosp-clang }} == false ]; then
            echo "Using prebuilt clang"
         else
            if [ ${{ inputs.aosp-clang }} == "11" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz
            elif [ ${{ inputs.aosp-clang }} == "13" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz
            elif [ ${{ inputs.aosp-clang }} == "14" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz
            elif [ ${{ inputs.aosp-clang }} == "19" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz
            elif [ ${{ inputs.aosp-clang }} == "20" ]; then
                aria2c -o aosp-clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-9.0.0_r3/clang-4691093.tar.gz
            elif [ ${{ inputs.aosp-clang }} != false ]; then
                aria2c -o aosp-clang.tar.gz ${{ inputs.aosp-clang }}
            fi
            mkdir $HOME/clang -p -v
            tar -C $HOME/clang -zxf aosp-clang.tar.gz
         fi
    - name: Setup Kernel
      run: |
         if [ ${{ inputs.kernel-url }} != false ]; then
            git clone --depth=1 ${{ inputs.kernel-url }} -b ${{ inputs.kernel-branch }} kernel-dir
         else
            ls
         fi
    - name: LTO
      run: |
         if [ ${{ inputs.kernel-url }} != false ]; then
            cd kernel-dir
         fi
         if [ ${{ inputs.disable-lto }} = true ]; then
             if grep -q "LTO" "arch/arm64/configs/${{ inputs.kernel-config }}"
             then
                  sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  echo "CONFIG_LTO_NONE=y" | tee -a arch/arm64/configs/${{ inputs.kernel-config }} >/dev/null
             fi
         fi
    - name: Compile
      run: |
         mkdir out -p -v
         if [ ${{ inputs.kernel-url }} != false ]; then
            cd kernel-dir
            COMMAND="make -j$(nproc --all) ${{ inputs.kernel-config }} ARCH=arm64 O=../out all"
         fi
         if [ ${{ inputs.kernel-url }} == false ]; then
            COMMAND="make -j$(nproc --all) ${{ inputs.kernel-config }} ARCH=arm64 O=out all"
         fi
         if [ ${{ inputs.aosp-clang }} == false ]; then
            echo "Using prebuilt gcc and clang"
         else
            export PATH=$HOME/clang/bin:$HOME/gcc-64/bin:$HOME/gcc-32:$PATH
         fi
         export KBUILD_BUILD_USER="malkist"
         export KBUILD_BUILD_HOST="android"
         export SUBLEVEL=$(cat Makefile | grep "PATCHLEVEL =" | awk '{print $3}')
         if [ ${{ inputs.aosp-clang }} == false ]; then
                COMMAND+=" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi-"
         else
                COMMAND+=" CROSS_COMPILE=aarch64-linux-android- COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu-"
         fi
         if [ ${{ inputs.compiler }} == clang ]; then
            COMMAND+=" CC=clang"
         elif [ ${{ inputs.compiler }} == llvm ]; then
            COMMAND+=" CC=clang"
            COMMAND+=" LLVM=1"
            COMMAND+=" LLVM_IAS=1"
            COMMAND+=" AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar"
            # COMMAND+=" LD=ld.lld HOSTLD=ld.lld"
         elif [ ${{ inputs.compiler }} == clang2 ]; then
            COMMAND+=" CC=clang"
            COMMAND+=" ${{ inputs.command }}"
         elif [ ${{ inputs.compiler }} == llvm2 ]; then
            COMMAND+=" CC=clang"
            COMMAND+=" LLVM=1"
            COMMAND+=" LLVM_IAS=1"
            COMMAND+=" AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar"
            # COMMAND+=" LD=ld.lld HOSTLD=ld.lld"
            COMMAND+=" ${{ inputs.command }}"
         elif [ ${{ inputs.compiler }} == other ]; then
            COMMAND+=" ${{ inputs.command }}"
         fi
         ${COMMAND}
    - name: Create flashable.zip
      run: |
          git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md AnyKernel3/modules AnyKernel3/patch AnyKernel3/ramdisk
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
    - name: Upload Artifact
      run: |
          mkdir Upload
          cp -rf AnyKernel3/* Upload
    - id: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: Upload/*
# Enjoy Your Life....
